vim.opt.number = true
vim.opt.showmode = false
-- vim.opt.clipboard = "unnamedplus"
vim.opt.tabstop = 4
vim.opt.expandtab = false
vim.opt.shiftwidth = 4
vim.opt.wrap = false
vim.opt.termguicolors = true
vim.opt.colorcolumn = { 80, 120 }
vim.opt.foldlevel = 99
vim.opt.foldlevelstart = 99
vim.opt.laststatus = 3
vim.opt.signcolumn = "no"
